import React,{useState} from "react";
import '../CSS/footer.css';

//Iconos
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faInstagram,faSquareXTwitter } from "@fortawesome/free-brands-svg-icons";

export default function Footer(){

    const [isHover,setIsHover ] = useState(false);

return (
    <>
    <footer>
        <h4 className="contact">
            CONTACTA:
        </h4>

        <p className="correo">
            <a href="mailto:martinacabreramua89@gmail.com">martinacabreramua89@gmail.com</a>
        </p>

        <div className='redesFooter'>
            <FontAwesomeIcon icon={faInstagram}
            className={isHover ? 'animate__animated animate__fadeInUp' : 'animate__animated'}
            onMouseEnter={() => setIsHover(true)}
            onMouseLeave={() => setIsHover(false)}  size="2x" style={{color: "#11114"}}/>

            <FontAwesomeIcon className={isHover ? 'animate__animated animate__fadeInUp' : 'animate__animated'}
            onMouseEnter={() => setIsHover(true)}
            onMouseLeave={() => setIsHover(false)}  icon={faSquareXTwitter} size="2x" style={{color: "white"}} />
        </div>

        <span>© Martina Cabrera - Make up Artist</span>
        <span>Generated by Danna Max</span>
    </footer>

    </>
)
}